#===============COMPULSORY PROGRAM ARGUMENTS=====#
mongo-server:
#===============COMPULSORY PROGRAM ARGUMENTS=====#

server:
  port: 8082

spring:
  data:
    mongodb:
      uri: ${mongo-server}

gwas-ingest-service:
  #db: deposition-backend-sandbox
  db: gwasdepo
  service-environments: dev

quartz:
  scheduler:
    #dbName: gwas-deposition-dev
    dbName: gwasdepo
