server:
  port: 8080

spring:
  data:
    mongodb:
      uri: production.bok3f.mongodb.net/test?retryWrites=true&w=majority
#      uri: mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039

gwas-ingest-service:
  db: gwasdepo
  service-environments: prod, prod-fallback

quartz:
  scheduler:
    dbName: gwasdepo
