server:
  port: 8080
  servlet:
    context-path: /gwas/ingest/api

spring:
  data:
    mongodb:
      #uri: mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039
      uri: mongodb-hx-gwasdepopro-001.ebi.ac.uk:27017,mongodb-hl-gwasdepopro-002.ebi.ac.uk:27017/admin?replicaSet=gwasdepoprors080

gwas-ingest-service:
  db: gwasdepo
  service-environments: prod, prod-fallback

quartz:
  scheduler:
    dbName: gwasdepo


rabbitmq:
  queue-name: study_change_sandbox
  exchange-name: study_change_exchange_sandbox
  routing-key: study-ingest_sandbox
  sumstats:
    queue-name: metadata-yml-update
    exchange-name: metadata-yml-update-exchange
    routing-key: metadata-yml-update-route