server:
  port: 8080

spring:
  data:
    mongodb:
      uri: localhost:27017

gwas-ingest-service:
  db: gwas-deposition-dev
  service-environments: dev

quartz:
  scheduler:
    dbName: gwas-deposition-dev