server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb-hx-gwasdepopro-001:27017,mongodb-hl-gwasdepopro-002:27017/admin?replicaSet=gwasdepoprors080

gwas-ingest-service:
  db: gwasdepo
  service-environments: prod, prod-fallback

quartz:
  scheduler:
    dbName: gwasdepo
