server:
  name: deposition-ingest-service
  port: 80

logging:
  level:
    org:
      springframework:
        web: DEBUG

gwas-ingest-service:
  auto-curator-service-account: auto-curator-service@ebi.ac.uk
  auth:
    enabled: false
  service-environments: dev

audit:
  enabled: false
  url: http://gwas-audit-service:8080
  endpoints:
    audit-entries: /v1/audit-entries

quartz:
  scheduler:
    active: false

spring:
  profiles:
    active: local

comms:
  messaging:
    enabled: false
