server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongo-0.mongo.gwas-dev.svc.cluster.local,mongo-1.mongo.gwas-dev.svc.cluster.local,mongo-2.mongo.gwas-dev.svc.cluster.local:27017

gwas-ingest-service:
  db: deposition-backend-sandbox
  service-environments: sandbox

quartz:
  scheduler:
    dbName: deposition-backend-sandbox
