server:
  port: 8080

spring:
  data:
    mongodb:
      uri: production-shard-00-02.bok3f.mongodb.net:27017,production-shard-00-01.bok3f.mongodb.net:27017,production-shard-00-00.bok3f.mongodb.net:27017/test?authSource=admin&gssapiServiceName=mongodb&replicaSet=atlas-ogm2wz-shard-0&ssl=true
#      uri: mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039

gwas-ingest-service:
  db: gwasdepo
  service-environments: prod, prod-fallback

quartz:
  scheduler:
    dbName: gwasdepo
