server:
  port: 8080
  servlet:
    context-path: /gwas/ingest/api

spring:
  data:
    mongodb:
      #uri: mongo-0.mongo.gwas-dev.svc.cluster.local,mongo-1.mongo.gwas-dev.svc.cluster.local,mongo-2.mongo.gwas-dev.svc.cluster.local:27017
      uri: mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039

gwas-ingest-service:
  #db: deposition-backend-sandbox
  db: gwasdepo
  service-environments: sandbox

quartz:
  scheduler:
    #dbName: deposition-backend-sandbox
    dbName: gwasdepo
