# Default values for gwas-ingest-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ebispot/gwas-deposition-ingest
  tag: latest
  pullPolicy: Always
  containerPort: 8080
  logMountPath: "/var/log/gwas"
  env:
    envName: "sandbox"
    logFileName: "ingest-service"
    xms: "-Xms512m"
    xmx: "-Xms512m"
    dbUser: ""
    secretsName: ""
    secretsKey: ""
  volume:
    claimName: gwas-depo-logs

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  name: gwas-ingest-service
  type: NodePort
  port: 8080

k8Namespace: default

ingress:
  enabled: false

resources:
  limits:
    cpu: 50m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
