environments:
- name: dev
  config: application-dev.yml
  dev: true
  gcp: false
- name: test
  config: application-test.yml
  dev: true
  gcp: false
- name: sandbox
  config: application-sandbox.yml
  dev: false
  gcp: false
- name: prod
  config: application-prod.yml
  dev: false
  gcp: false
- name: gcp-sandbox
  config: application-gcp-sandbox.yml
  dev: false
  gcp: true
